### ISSUE TITLE
Move PATH command

### ISSUE THREAD

**Issue by Auronius** [corbindavenport/nexus-tools#70]
Good day!
I have installed nexustools to my Linux Mint 20.3 Una.
The program has been installed successfully, but adding the directory to systems path did not worked. After some help in Linux Mint forum, I have been adviced, that instead of creating **~/.bash_profile** file, the script should add path information to **~./profile**. Then it works correctly. That is because the login shell is not bash on Ubuntu/Mint/Debian but dash.
**Please look at this topic:** https://forums.linuxmint.com/viewtopic.php?p=2297663#p2297663

**Comment by corbindavenport** [comment]
Weird, I didn't know Linux Mint behaved differently there. I'll look into this, I need to check how other distributions (and macOS) behave in comparison and make sure changing it to `~./profile` won't break something else.

**Comment by corbindavenport** [comment]
I booted up Linux Mint 21.3 on a live CD and it appears to be using bash as the default shell. I tried installing dash on my Mac to test how it handles PATH variables, but it's a bit annoying to test because I think it's reading the variables already set in bash.

The order of operations for `~./profile` and `~/.bash_profile` is also pretty complicated: https://unix.stackexchange.com/a/45734

I haven't seen this issue brought up elsewhere, so for now I'm going to avoid rocking the boat and changing where the PATH variable is set, because it could cause issues on other operating systems. If someone wants to create a PR adding explicit support for more shells to the `addPath()` command with the required detection, I can definitely accept it.
